### ISSUE TITLE
uvicorn command not found at Step 6 of "Running the backend" of Project Setup

### ISSUE THREAD

**Issue by GnohChengYi** [geoboom/facemask-workshop#1]
I ran into the issue of `./run.sh: line 2: uvicorn: command not found` at Step 6 of "[Running the backend (FastAPI server)](https://github.com/geoboom/facemask-workshop/blob/master/README.md#running-the-backend-fastapi-server)".

Note that at Step 5, I encounter the following errors:
`ERROR: Could not find a version that satisfies the requirement opencv-contrib-python==4.4.0.42 (from -r requirements.txt (line 28)) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.1.2.30, 4.2.0.32, 4.2.0.34)`
`ERROR: No matching distribution found for opencv-contrib-python==4.4.0.42 (from -r requirements.txt (line 28))`
and the following warning:
`WARNING: You are using pip version 19.2.3, however version 20.2.3 is available.`
`You should consider upgrading via the 'pip install --upgrade pip' command.`

Please guide me on solving the issue. Thanks!

**Comment by geoboom** [comment]
Hi! Thanks for the question.

Kindly try running `python3 --version` and pasting the output. Also, try upgrading pip using `pip install -upgrade pip` then re-running `source venv/bin/activate` and `pip install -r requirements.txt` (while in the backend folder). Let me know how it goes. :) 

I think the error is likely due to your version of python or pip not supporting the project's versions of libraries like opencv-contrib-python 4.4, in which case I'll update the requirements.txt to use a lower version of some libraries for better support overall.

**Comment by nicoleang09** [comment]
Hi, I am having the same issue and I've tried upgrading pip, but it still gives the same error `./run.sh: line 2: uvicorn: command not found`. My Python version is 3.8.3. Is it the correct version?

**Comment by geoboom** [comment]
So sorry everyone:pray:. Currently trying the setup and diagnosing the issue on fresh machines. Will let you know when we've found a fix!

**In the meantime, you could try this workaround:**
1. Run `source venv/bin/activate` while in the **backend/** folder.
2. Run `pip install opencv-contrib-python` to install the `opencv-contrib-python` library manually. This should automatically install a version of the library compatible with your environment's python version.
3. Then run `pip install -r requirements.txt` to install the remaining dependencies.

**One last thing:** could you provide me with your operating system (Mac/Linux/Windows) details? Much thanks!

EDIT: formatting

**Comment by nicoleang09** [comment]
That worked, thanks! I'm running on Windows 10.

**Comment by GnohChengYi** [comment]
That worked for me too, thanks!

**Comment by geoboom** [comment]
Welcome! I've updated the repo with another version of `opencv-contrib-python` so you can `git pull` (to fetch the latest updates) in the project directory and run `pip install -r requirements.txt` in the backend folder to install everything.
